export const queryKeys = {
  auth: {
    currentUser: ["auth", "current-user"] as const,
  },
  catalog: {
    bootstrap: ["catalog", "bootstrap"] as const,
    products: ["catalog", "products"] as const,
    productsList: (params: Record<string, unknown>) => ["catalog", "products", params] as const,
    categories: ["catalog", "categories"] as const,
    brands: ["catalog", "brands"] as const,
    settings: ["catalog", "settings"] as const,
    shippingZones: ["catalog", "shipping-zones"] as const,
    product: (slug: string) => ["catalog", "product", slug] as const,
  },
  admin: {
    dashboard: ["admin", "dashboard"] as const,
    dashboardRange: (params: Record<string, unknown>) => ["admin", "dashboard", params] as const,
    products: ["admin", "products"] as const,
    inventorySnapshot: ["admin", "inventory", "snapshot"] as const,
    inventoryLedger: ["admin", "inventory", "ledger"] as const,
    inventoryLedgerList: (params: Record<string, unknown>) => ["admin", "inventory", "ledger", params] as const,
    categories: ["admin", "categories"] as const,
    brands: ["admin", "brands"] as const,
    orders: ["admin", "orders"] as const,
    ordersList: (params: Record<string, unknown>) => ["admin", "orders", params] as const,
    customers: ["admin", "customers"] as const,
    customersList: (params: Record<string, unknown>) => ["admin", "customers", params] as const,
    employees: ["admin", "employees"] as const,
    returns: ["admin", "returns"] as const,
    settings: ["admin", "settings"] as const,
    commissions: ["admin", "commissions"] as const,
    commissionsList: (params: Record<string, unknown>) => ["admin", "commissions", params] as const,
    posSales: ["admin", "pos-sales"] as const,
    posSalesList: (params: Record<string, unknown>) => ["admin", "pos-sales", params] as const,
    syncDiagnostics: ["admin", "sync-diagnostics"] as const,
    reports: (params: Record<string, unknown>) => ["admin", "reports", params] as const,
    fileMaintenance: ["admin", "file-maintenance"] as const,
  },
  pos: {
    bootstrap: (deviceKey: string, cursor?: string | null) => ["pos", "bootstrap", deviceKey, cursor ?? "none"] as const,
    products: ["pos", "products"] as const,
    employees: ["pos", "employees"] as const,
    settings: ["pos", "settings"] as const,
  },
  account: {
    profile: ["account", "profile"] as const,
    orders: ["account", "orders"] as const,
    addresses: ["account", "addresses"] as const,
  },
};
